<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="network" nsURI="http://s144449s144456.railwaymodelgenerator/network"
    nsPrefix="nw">
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlBoxes" upperBound="-1"
        eType="#//ControlBox" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="segments" upperBound="-1"
        eType="#//Segment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trains" upperBound="-1"
        eType="#//Train" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lockLimit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reserveLimit" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlBox" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ingoing" upperBound="3"
        eType="#//Segment" eOpposite="#//Segment/end"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="3"
        eType="#//Segment" eOpposite="#//Segment/start"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Segment" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//ControlBox"
        eOpposite="#//ControlBox/outgoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//ControlBox"
        eOpposite="#//ControlBox/ingoing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentOneWay" eSuperTypes="#//Segment"/>
  <eClassifiers xsi:type="ecore:EClass" name="SegmentTwoWay" eSuperTypes="#//Segment"/>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchBox" eSuperTypes="#//ControlBox">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connected" lowerBound="1"
        eType="#//PointSetting"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stem" lowerBound="1" eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plus" lowerBound="1" eType="#//Segment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="minus" lowerBound="1" eType="#//Segment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PointSetting">
    <eLiterals name="PLUS"/>
    <eLiterals name="MINUS" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegularBox" eSuperTypes="#//ControlBox"/>
  <eClassifiers xsi:type="ecore:EClass" name="Train" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="route" lowerBound="1" upperBound="-1"
        eType="#//Segment"/>
  </eClassifiers>
</ecore:EPackage>
